add_library(
    inferlite_core
    STATIC
    core/version.cpp
    core/status.cpp
    core/tensor.cpp
)
target_link_libraries(
    inferlite_core
    PRIVATE
        inferlite_project_options
         inferlite_sanitizers
)
target_include_directories(
    inferlite_core
    PUBLIC
        ${PROJECT_SOURCE_DIR}/include
)